FROM golang:latest as builder

COPY . /server
WORKDIR /server
ENV GO111MODULE=on
RUN CGO_ENABLED=0 GOOOS=linux go build -o serverexec ./server/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /server .
CMD ["./serverexec"]